"""
Profitable strategy generated by Genetic Algorithm evolution.
"""

from freqtrade.strategy import IStrategy
from pandas import DataFrame
import talib.abstract as ta


class GAProfitableStrategy(IStrategy):
    """
    Profitable trading strategy evolved using genetic algorithms.
    """
    
    # Strategy interface version
    INTERFACE_VERSION = 3
    
    # Minimal ROI designed for the strategy
    minimal_roi = {
        "0": 0.05,  # 5% profit
        "120": 0.03,  # 3% profit after 5 days
        "240": 0.01,  # 1% profit after 10 days
    }
    
    # Stoploss
    stoploss = -0.06
    
    # Trailing stop
    trailing_stop = False
    
    # Optimal timeframe
    timeframe = '1h'
    
    # Run "populate_indicators" only for new candle.
    process_only_new_candles = False
    
    # These values can be overridden in the "ask_strategy" section in the config.
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_exit_signal = False
    
    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 30
    
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Populate technical indicators.
        """
        
        # RSI
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        
        # MACD
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        
        # EMA
        dataframe['ema_20'] = ta.EMA(dataframe, timeperiod=20)
        dataframe['ema_50'] = ta.EMA(dataframe, timeperiod=50)
        
        # ATR
        dataframe['atr'] = ta.ATR(dataframe, timeperiod=14)
        
        # Bollinger Bands using talib
        dataframe['bb_upperband'], dataframe['bb_middleband'], dataframe['bb_lowerband'] = ta.BBANDS(
            dataframe, timeperiod=20, nbdevup=2.0, nbdevdn=2.0
        )
        
        return dataframe
    
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Populate buy signals based on DNA thresholds.
        """
        
        # More selective trend-following strategy
        dataframe.loc[
            (
                (dataframe['ema_20'] > dataframe['ema_50']) &
                (dataframe['ema_50'] > dataframe['ema_100']) &
                (dataframe['ema_20'] > dataframe['ema_20'].shift(1)) &
                (dataframe['rsi'] > 55) &
                (dataframe['rsi'] < 70) &
                (dataframe['macd'] > dataframe['macdsignal'])
            ),
            'buy'
        ] = 1
        
        return dataframe
    
    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Populate sell signals based on DNA thresholds.
        """
        
        # Simple trend-following exit
        dataframe.loc[
            (
                (dataframe['ema_20'] < dataframe['ema_50']) |
                (dataframe['rsi'] > 75)
            ),
            'sell'
        ] = 1
        
        return dataframe
